# Generated by Django 4.2.1 on 2023-05-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_usefullink_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usefullink',
            name='body',
        ),
    ]
