# Generated by Django 4.2.1 on 2023-06-16 23:23

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to=articles.models.article_directory_path),
        ),
    ]
